# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  reviewers:
  - planetf1
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  reviewers:
  - planetf1
