# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Docker"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Docker"
    env:
      RELEASE_VERSION: 3.1-SNAPSHOT
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        if: ${{ github.event_name == 'push' && github.repository == 'planetf1/atlas-docker' && github.ref == 'refs/heads/main' }}
      - name: Build and push (main merge)
        if: ${{ github.event_name == 'push' && github.repository == 'planetf1/atlas-docker' && github.ref == 'refs/heads/main' }}
        id: docker_build_main
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: planetf1/atlas-docker:${{ env.RELEASE_VERSION}}, planetf1/atlas-docker:latest
          build-args: version=${{ env.RELEASE_VERSION }}
          context: .
          file: ./Dockerfile
      - name: Build only (PR verify)
        if: ${{ github.event_name == 'pull_request' }}
        id: docker_build_main
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: planetf1/atlas-docker:${{ env.RELEASE_VERSION}}-prtest
          build-args: version=${{ env.RELEASE_VERSION }}
          context: .
          file: ./Dockerfile
